// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum FixedSizeListOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FixedSizeList<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for FixedSizeList<'a> {
  type Inner = FixedSizeList<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> FixedSizeList<'a> {
  pub const VT_LISTSIZE: flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "FixedSizeList"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    FixedSizeList { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args FixedSizeListArgs
  ) -> flatbuffers::WIPOffset<FixedSizeList<'bldr>> {
    let mut builder = FixedSizeListBuilder::new(_fbb);
    builder.add_listSize(args.listSize);
    builder.finish()
  }

  pub fn unpack(&self) -> FixedSizeListT {
    let listSize = self.listSize();
    FixedSizeListT {
      listSize,
    }
  }

  /// Number of list items per value
  #[inline]
  pub fn listSize(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(FixedSizeList::VT_LISTSIZE, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for FixedSizeList<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("listSize", Self::VT_LISTSIZE, false)?
     .finish();
    Ok(())
  }
}
pub struct FixedSizeListArgs {
    pub listSize: i32,
}
impl<'a> Default for FixedSizeListArgs {
  #[inline]
  fn default() -> Self {
    FixedSizeListArgs {
      listSize: 0,
    }
  }
}

pub struct FixedSizeListBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> FixedSizeListBuilder<'a, 'b> {
  #[inline]
  pub fn add_listSize(&mut self, listSize: i32) {
    self.fbb_.push_slot::<i32>(FixedSizeList::VT_LISTSIZE, listSize, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> FixedSizeListBuilder<'a, 'b> {
    let start = _fbb.start_table();
    FixedSizeListBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FixedSizeList<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FixedSizeList<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FixedSizeList");
      ds.field("listSize", &self.listSize());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct FixedSizeListT {
  pub listSize: i32,
}
impl Default for FixedSizeListT {
  fn default() -> Self {
    Self {
      listSize: 0,
    }
  }
}
impl FixedSizeListT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<FixedSizeList<'b>> {
    let listSize = self.listSize;
    FixedSizeList::create(_fbb, &FixedSizeListArgs{
      listSize,
    })
  }
}
