// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum FixedSizeBinaryOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FixedSizeBinary<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for FixedSizeBinary<'a> {
  type Inner = FixedSizeBinary<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> FixedSizeBinary<'a> {
  pub const VT_BYTEWIDTH: flatbuffers::VOffsetT = 4;

  pub const fn get_fully_qualified_name() -> &'static str {
    "FixedSizeBinary"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    FixedSizeBinary { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args FixedSizeBinaryArgs
  ) -> flatbuffers::WIPOffset<FixedSizeBinary<'bldr>> {
    let mut builder = FixedSizeBinaryBuilder::new(_fbb);
    builder.add_byteWidth(args.byteWidth);
    builder.finish()
  }

  pub fn unpack(&self) -> FixedSizeBinaryT {
    let byteWidth = self.byteWidth();
    FixedSizeBinaryT {
      byteWidth,
    }
  }

  /// Number of bytes per value
  #[inline]
  pub fn byteWidth(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(FixedSizeBinary::VT_BYTEWIDTH, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for FixedSizeBinary<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i32>("byteWidth", Self::VT_BYTEWIDTH, false)?
     .finish();
    Ok(())
  }
}
pub struct FixedSizeBinaryArgs {
    pub byteWidth: i32,
}
impl<'a> Default for FixedSizeBinaryArgs {
  #[inline]
  fn default() -> Self {
    FixedSizeBinaryArgs {
      byteWidth: 0,
    }
  }
}

pub struct FixedSizeBinaryBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> FixedSizeBinaryBuilder<'a, 'b> {
  #[inline]
  pub fn add_byteWidth(&mut self, byteWidth: i32) {
    self.fbb_.push_slot::<i32>(FixedSizeBinary::VT_BYTEWIDTH, byteWidth, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> FixedSizeBinaryBuilder<'a, 'b> {
    let start = _fbb.start_table();
    FixedSizeBinaryBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<FixedSizeBinary<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for FixedSizeBinary<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("FixedSizeBinary");
      ds.field("byteWidth", &self.byteWidth());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct FixedSizeBinaryT {
  pub byteWidth: i32,
}
impl Default for FixedSizeBinaryT {
  fn default() -> Self {
    Self {
      byteWidth: 0,
    }
  }
}
impl FixedSizeBinaryT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<FixedSizeBinary<'b>> {
    let byteWidth = self.byteWidth;
    FixedSizeBinary::create(_fbb, &FixedSizeBinaryArgs{
      byteWidth,
    })
  }
}
