// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_TYPE: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_TYPE: u8 = 21;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_TYPE: [Type; 22] = [
  Type::NONE,
  Type::Null,
  Type::Int,
  Type::FloatingPoint,
  Type::Binary,
  Type::Utf8,
  Type::Bool,
  Type::Decimal,
  Type::Date,
  Type::Time,
  Type::Timestamp,
  Type::Interval,
  Type::List,
  Type::Struct_,
  Type::Union,
  Type::FixedSizeBinary,
  Type::FixedSizeList,
  Type::Map,
  Type::Duration,
  Type::LargeBinary,
  Type::LargeUtf8,
  Type::LargeList,
];

/// ----------------------------------------------------------------------
/// Top-level Type value, enabling extensible type-specific metadata. We can
/// add new logical types to Type without breaking backwards compatibility
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Type(pub u8);
#[allow(non_upper_case_globals)]
impl Type {
  pub const NONE: Self = Self(0);
  pub const Null: Self = Self(1);
  pub const Int: Self = Self(2);
  pub const FloatingPoint: Self = Self(3);
  pub const Binary: Self = Self(4);
  pub const Utf8: Self = Self(5);
  pub const Bool: Self = Self(6);
  pub const Decimal: Self = Self(7);
  pub const Date: Self = Self(8);
  pub const Time: Self = Self(9);
  pub const Timestamp: Self = Self(10);
  pub const Interval: Self = Self(11);
  pub const List: Self = Self(12);
  pub const Struct_: Self = Self(13);
  pub const Union: Self = Self(14);
  pub const FixedSizeBinary: Self = Self(15);
  pub const FixedSizeList: Self = Self(16);
  pub const Map: Self = Self(17);
  pub const Duration: Self = Self(18);
  pub const LargeBinary: Self = Self(19);
  pub const LargeUtf8: Self = Self(20);
  pub const LargeList: Self = Self(21);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 21;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::Null,
    Self::Int,
    Self::FloatingPoint,
    Self::Binary,
    Self::Utf8,
    Self::Bool,
    Self::Decimal,
    Self::Date,
    Self::Time,
    Self::Timestamp,
    Self::Interval,
    Self::List,
    Self::Struct_,
    Self::Union,
    Self::FixedSizeBinary,
    Self::FixedSizeList,
    Self::Map,
    Self::Duration,
    Self::LargeBinary,
    Self::LargeUtf8,
    Self::LargeList,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::Null => Some("Null"),
      Self::Int => Some("Int"),
      Self::FloatingPoint => Some("FloatingPoint"),
      Self::Binary => Some("Binary"),
      Self::Utf8 => Some("Utf8"),
      Self::Bool => Some("Bool"),
      Self::Decimal => Some("Decimal"),
      Self::Date => Some("Date"),
      Self::Time => Some("Time"),
      Self::Timestamp => Some("Timestamp"),
      Self::Interval => Some("Interval"),
      Self::List => Some("List"),
      Self::Struct_ => Some("Struct_"),
      Self::Union => Some("Union"),
      Self::FixedSizeBinary => Some("FixedSizeBinary"),
      Self::FixedSizeList => Some("FixedSizeList"),
      Self::Map => Some("Map"),
      Self::Duration => Some("Duration"),
      Self::LargeBinary => Some("LargeBinary"),
      Self::LargeUtf8 => Some("LargeUtf8"),
      Self::LargeList => Some("LargeList"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for Type {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for Type {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for Type {
    type Output = Type;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for Type {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for Type {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Type {}
pub struct TypeUnionTableOffset {}

#[allow(clippy::upper_case_acronyms)]
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub enum TypeT {
  NONE,
  Null(Box<NullT>),
  Int(Box<IntT>),
  FloatingPoint(Box<FloatingPointT>),
  Binary(Box<BinaryT>),
  Utf8(Box<Utf8T>),
  Bool(Box<BoolT>),
  Decimal(Box<DecimalT>),
  Date(Box<DateT>),
  Time(Box<TimeT>),
  Timestamp(Box<TimestampT>),
  Interval(Box<IntervalT>),
  List(Box<ListT>),
  Struct_(Box<Struct_T>),
  Union(Box<UnionT>),
  FixedSizeBinary(Box<FixedSizeBinaryT>),
  FixedSizeList(Box<FixedSizeListT>),
  Map(Box<MapT>),
  Duration(Box<DurationT>),
  LargeBinary(Box<LargeBinaryT>),
  LargeUtf8(Box<LargeUtf8T>),
  LargeList(Box<LargeListT>),
}
impl Default for TypeT {
  fn default() -> Self {
    Self::NONE
  }
}
impl TypeT {
  pub fn type_type(&self) -> Type {
    match self {
      Self::NONE => Type::NONE,
      Self::Null(_) => Type::Null,
      Self::Int(_) => Type::Int,
      Self::FloatingPoint(_) => Type::FloatingPoint,
      Self::Binary(_) => Type::Binary,
      Self::Utf8(_) => Type::Utf8,
      Self::Bool(_) => Type::Bool,
      Self::Decimal(_) => Type::Decimal,
      Self::Date(_) => Type::Date,
      Self::Time(_) => Type::Time,
      Self::Timestamp(_) => Type::Timestamp,
      Self::Interval(_) => Type::Interval,
      Self::List(_) => Type::List,
      Self::Struct_(_) => Type::Struct_,
      Self::Union(_) => Type::Union,
      Self::FixedSizeBinary(_) => Type::FixedSizeBinary,
      Self::FixedSizeList(_) => Type::FixedSizeList,
      Self::Map(_) => Type::Map,
      Self::Duration(_) => Type::Duration,
      Self::LargeBinary(_) => Type::LargeBinary,
      Self::LargeUtf8(_) => Type::LargeUtf8,
      Self::LargeList(_) => Type::LargeList,
    }
  }
  pub fn pack(&self, fbb: &mut flatbuffers::FlatBufferBuilder) -> Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>> {
    match self {
      Self::NONE => None,
      Self::Null(v) => Some(v.pack(fbb).as_union_value()),
      Self::Int(v) => Some(v.pack(fbb).as_union_value()),
      Self::FloatingPoint(v) => Some(v.pack(fbb).as_union_value()),
      Self::Binary(v) => Some(v.pack(fbb).as_union_value()),
      Self::Utf8(v) => Some(v.pack(fbb).as_union_value()),
      Self::Bool(v) => Some(v.pack(fbb).as_union_value()),
      Self::Decimal(v) => Some(v.pack(fbb).as_union_value()),
      Self::Date(v) => Some(v.pack(fbb).as_union_value()),
      Self::Time(v) => Some(v.pack(fbb).as_union_value()),
      Self::Timestamp(v) => Some(v.pack(fbb).as_union_value()),
      Self::Interval(v) => Some(v.pack(fbb).as_union_value()),
      Self::List(v) => Some(v.pack(fbb).as_union_value()),
      Self::Struct_(v) => Some(v.pack(fbb).as_union_value()),
      Self::Union(v) => Some(v.pack(fbb).as_union_value()),
      Self::FixedSizeBinary(v) => Some(v.pack(fbb).as_union_value()),
      Self::FixedSizeList(v) => Some(v.pack(fbb).as_union_value()),
      Self::Map(v) => Some(v.pack(fbb).as_union_value()),
      Self::Duration(v) => Some(v.pack(fbb).as_union_value()),
      Self::LargeBinary(v) => Some(v.pack(fbb).as_union_value()),
      Self::LargeUtf8(v) => Some(v.pack(fbb).as_union_value()),
      Self::LargeList(v) => Some(v.pack(fbb).as_union_value()),
    }
  }
  /// If the union variant matches, return the owned NullT, setting the union to NONE.
  pub fn take_null(&mut self) -> Option<Box<NullT>> {
    if let Self::Null(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Null(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the NullT.
  pub fn as_null(&self) -> Option<&NullT> {
    if let Self::Null(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the NullT.
  pub fn as_null_mut(&mut self) -> Option<&mut NullT> {
    if let Self::Null(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned IntT, setting the union to NONE.
  pub fn take_int(&mut self) -> Option<Box<IntT>> {
    if let Self::Int(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Int(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the IntT.
  pub fn as_int(&self) -> Option<&IntT> {
    if let Self::Int(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the IntT.
  pub fn as_int_mut(&mut self) -> Option<&mut IntT> {
    if let Self::Int(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned FloatingPointT, setting the union to NONE.
  pub fn take_floating_point(&mut self) -> Option<Box<FloatingPointT>> {
    if let Self::FloatingPoint(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::FloatingPoint(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the FloatingPointT.
  pub fn as_floating_point(&self) -> Option<&FloatingPointT> {
    if let Self::FloatingPoint(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the FloatingPointT.
  pub fn as_floating_point_mut(&mut self) -> Option<&mut FloatingPointT> {
    if let Self::FloatingPoint(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned BinaryT, setting the union to NONE.
  pub fn take_binary(&mut self) -> Option<Box<BinaryT>> {
    if let Self::Binary(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Binary(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the BinaryT.
  pub fn as_binary(&self) -> Option<&BinaryT> {
    if let Self::Binary(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the BinaryT.
  pub fn as_binary_mut(&mut self) -> Option<&mut BinaryT> {
    if let Self::Binary(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned Utf8T, setting the union to NONE.
  pub fn take_utf_8(&mut self) -> Option<Box<Utf8T>> {
    if let Self::Utf8(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Utf8(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the Utf8T.
  pub fn as_utf_8(&self) -> Option<&Utf8T> {
    if let Self::Utf8(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the Utf8T.
  pub fn as_utf_8_mut(&mut self) -> Option<&mut Utf8T> {
    if let Self::Utf8(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned BoolT, setting the union to NONE.
  pub fn take_bool(&mut self) -> Option<Box<BoolT>> {
    if let Self::Bool(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Bool(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the BoolT.
  pub fn as_bool(&self) -> Option<&BoolT> {
    if let Self::Bool(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the BoolT.
  pub fn as_bool_mut(&mut self) -> Option<&mut BoolT> {
    if let Self::Bool(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned DecimalT, setting the union to NONE.
  pub fn take_decimal(&mut self) -> Option<Box<DecimalT>> {
    if let Self::Decimal(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Decimal(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the DecimalT.
  pub fn as_decimal(&self) -> Option<&DecimalT> {
    if let Self::Decimal(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the DecimalT.
  pub fn as_decimal_mut(&mut self) -> Option<&mut DecimalT> {
    if let Self::Decimal(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned DateT, setting the union to NONE.
  pub fn take_date(&mut self) -> Option<Box<DateT>> {
    if let Self::Date(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Date(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the DateT.
  pub fn as_date(&self) -> Option<&DateT> {
    if let Self::Date(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the DateT.
  pub fn as_date_mut(&mut self) -> Option<&mut DateT> {
    if let Self::Date(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned TimeT, setting the union to NONE.
  pub fn take_time(&mut self) -> Option<Box<TimeT>> {
    if let Self::Time(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Time(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the TimeT.
  pub fn as_time(&self) -> Option<&TimeT> {
    if let Self::Time(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the TimeT.
  pub fn as_time_mut(&mut self) -> Option<&mut TimeT> {
    if let Self::Time(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned TimestampT, setting the union to NONE.
  pub fn take_timestamp(&mut self) -> Option<Box<TimestampT>> {
    if let Self::Timestamp(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Timestamp(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the TimestampT.
  pub fn as_timestamp(&self) -> Option<&TimestampT> {
    if let Self::Timestamp(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the TimestampT.
  pub fn as_timestamp_mut(&mut self) -> Option<&mut TimestampT> {
    if let Self::Timestamp(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned IntervalT, setting the union to NONE.
  pub fn take_interval(&mut self) -> Option<Box<IntervalT>> {
    if let Self::Interval(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Interval(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the IntervalT.
  pub fn as_interval(&self) -> Option<&IntervalT> {
    if let Self::Interval(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the IntervalT.
  pub fn as_interval_mut(&mut self) -> Option<&mut IntervalT> {
    if let Self::Interval(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned ListT, setting the union to NONE.
  pub fn take_list(&mut self) -> Option<Box<ListT>> {
    if let Self::List(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::List(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the ListT.
  pub fn as_list(&self) -> Option<&ListT> {
    if let Self::List(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the ListT.
  pub fn as_list_mut(&mut self) -> Option<&mut ListT> {
    if let Self::List(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned Struct_T, setting the union to NONE.
  pub fn take_struct_(&mut self) -> Option<Box<Struct_T>> {
    if let Self::Struct_(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Struct_(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the Struct_T.
  pub fn as_struct_(&self) -> Option<&Struct_T> {
    if let Self::Struct_(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the Struct_T.
  pub fn as_struct__mut(&mut self) -> Option<&mut Struct_T> {
    if let Self::Struct_(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned UnionT, setting the union to NONE.
  pub fn take_union(&mut self) -> Option<Box<UnionT>> {
    if let Self::Union(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Union(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the UnionT.
  pub fn as_union(&self) -> Option<&UnionT> {
    if let Self::Union(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the UnionT.
  pub fn as_union_mut(&mut self) -> Option<&mut UnionT> {
    if let Self::Union(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned FixedSizeBinaryT, setting the union to NONE.
  pub fn take_fixed_size_binary(&mut self) -> Option<Box<FixedSizeBinaryT>> {
    if let Self::FixedSizeBinary(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::FixedSizeBinary(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the FixedSizeBinaryT.
  pub fn as_fixed_size_binary(&self) -> Option<&FixedSizeBinaryT> {
    if let Self::FixedSizeBinary(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the FixedSizeBinaryT.
  pub fn as_fixed_size_binary_mut(&mut self) -> Option<&mut FixedSizeBinaryT> {
    if let Self::FixedSizeBinary(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned FixedSizeListT, setting the union to NONE.
  pub fn take_fixed_size_list(&mut self) -> Option<Box<FixedSizeListT>> {
    if let Self::FixedSizeList(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::FixedSizeList(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the FixedSizeListT.
  pub fn as_fixed_size_list(&self) -> Option<&FixedSizeListT> {
    if let Self::FixedSizeList(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the FixedSizeListT.
  pub fn as_fixed_size_list_mut(&mut self) -> Option<&mut FixedSizeListT> {
    if let Self::FixedSizeList(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned MapT, setting the union to NONE.
  pub fn take_map(&mut self) -> Option<Box<MapT>> {
    if let Self::Map(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Map(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the MapT.
  pub fn as_map(&self) -> Option<&MapT> {
    if let Self::Map(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the MapT.
  pub fn as_map_mut(&mut self) -> Option<&mut MapT> {
    if let Self::Map(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned DurationT, setting the union to NONE.
  pub fn take_duration(&mut self) -> Option<Box<DurationT>> {
    if let Self::Duration(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::Duration(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the DurationT.
  pub fn as_duration(&self) -> Option<&DurationT> {
    if let Self::Duration(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the DurationT.
  pub fn as_duration_mut(&mut self) -> Option<&mut DurationT> {
    if let Self::Duration(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned LargeBinaryT, setting the union to NONE.
  pub fn take_large_binary(&mut self) -> Option<Box<LargeBinaryT>> {
    if let Self::LargeBinary(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::LargeBinary(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the LargeBinaryT.
  pub fn as_large_binary(&self) -> Option<&LargeBinaryT> {
    if let Self::LargeBinary(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the LargeBinaryT.
  pub fn as_large_binary_mut(&mut self) -> Option<&mut LargeBinaryT> {
    if let Self::LargeBinary(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned LargeUtf8T, setting the union to NONE.
  pub fn take_large_utf_8(&mut self) -> Option<Box<LargeUtf8T>> {
    if let Self::LargeUtf8(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::LargeUtf8(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the LargeUtf8T.
  pub fn as_large_utf_8(&self) -> Option<&LargeUtf8T> {
    if let Self::LargeUtf8(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the LargeUtf8T.
  pub fn as_large_utf_8_mut(&mut self) -> Option<&mut LargeUtf8T> {
    if let Self::LargeUtf8(v) = self { Some(v.as_mut()) } else { None }
  }
  /// If the union variant matches, return the owned LargeListT, setting the union to NONE.
  pub fn take_large_list(&mut self) -> Option<Box<LargeListT>> {
    if let Self::LargeList(_) = self {
      let v = core::mem::replace(self, Self::NONE);
      if let Self::LargeList(w) = v {
        Some(w)
      } else {
        unreachable!()
      }
    } else {
      None
    }
  }
  /// If the union variant matches, return a reference to the LargeListT.
  pub fn as_large_list(&self) -> Option<&LargeListT> {
    if let Self::LargeList(v) = self { Some(v.as_ref()) } else { None }
  }
  /// If the union variant matches, return a mutable reference to the LargeListT.
  pub fn as_large_list_mut(&mut self) -> Option<&mut LargeListT> {
    if let Self::LargeList(v) = self { Some(v.as_mut()) } else { None }
  }
}
