// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;
use alloc::boxed::Box;
use alloc::string::{String, ToString};
use alloc::vec::Vec;
use core::mem;
use core::cmp::Ordering;
use self::flatbuffers::{EndianScalar, Follow};
use super::*;
pub enum UnionOffset {}
#[derive(Copy, Clone, PartialEq)]

/// A union is a complex type with children in Field
/// By default ids in the type vector refer to the offsets in the children
/// optionally typeIds provides an indirection between the child offset and the type id
/// for each child `typeIds[offset]` is the id used in the type vector
pub struct Union<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Union<'a> {
  type Inner = Union<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Union<'a> {
  pub const VT_MODE: flatbuffers::VOffsetT = 4;
  pub const VT_TYPEIDS: flatbuffers::VOffsetT = 6;

  pub const fn get_fully_qualified_name() -> &'static str {
    "Union"
  }

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Union { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args UnionArgs<'args>
  ) -> flatbuffers::WIPOffset<Union<'bldr>> {
    let mut builder = UnionBuilder::new(_fbb);
    if let Some(x) = args.typeIds { builder.add_typeIds(x); }
    builder.add_mode(args.mode);
    builder.finish()
  }

  pub fn unpack(&self) -> UnionT {
    let mode = self.mode();
    let typeIds = self.typeIds().map(|x| {
      x.into_iter().collect()
    });
    UnionT {
      mode,
      typeIds,
    }
  }

  #[inline]
  pub fn mode(&self) -> UnionMode {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<UnionMode>(Union::VT_MODE, Some(UnionMode::Sparse)).unwrap()}
  }
  #[inline]
  pub fn typeIds(&self) -> Option<flatbuffers::Vector<'a, i32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, i32>>>(Union::VT_TYPEIDS, None)}
  }
}

impl flatbuffers::Verifiable for Union<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<UnionMode>("mode", Self::VT_MODE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, i32>>>("typeIds", Self::VT_TYPEIDS, false)?
     .finish();
    Ok(())
  }
}
pub struct UnionArgs<'a> {
    pub mode: UnionMode,
    pub typeIds: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, i32>>>,
}
impl<'a> Default for UnionArgs<'a> {
  #[inline]
  fn default() -> Self {
    UnionArgs {
      mode: UnionMode::Sparse,
      typeIds: None,
    }
  }
}

pub struct UnionBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> UnionBuilder<'a, 'b> {
  #[inline]
  pub fn add_mode(&mut self, mode: UnionMode) {
    self.fbb_.push_slot::<UnionMode>(Union::VT_MODE, mode, UnionMode::Sparse);
  }
  #[inline]
  pub fn add_typeIds(&mut self, typeIds: flatbuffers::WIPOffset<flatbuffers::Vector<'b , i32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Union::VT_TYPEIDS, typeIds);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> UnionBuilder<'a, 'b> {
    let start = _fbb.start_table();
    UnionBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Union<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Union<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Union");
      ds.field("mode", &self.mode());
      ds.field("typeIds", &self.typeIds());
      ds.finish()
  }
}
#[non_exhaustive]
#[derive(Debug, Clone, PartialEq)]
pub struct UnionT {
  pub mode: UnionMode,
  pub typeIds: Option<Vec<i32>>,
}
impl Default for UnionT {
  fn default() -> Self {
    Self {
      mode: UnionMode::Sparse,
      typeIds: None,
    }
  }
}
impl UnionT {
  pub fn pack<'b>(
    &self,
    _fbb: &mut flatbuffers::FlatBufferBuilder<'b>
  ) -> flatbuffers::WIPOffset<Union<'b>> {
    let mode = self.mode;
    let typeIds = self.typeIds.as_ref().map(|x|{
      _fbb.create_vector(x)
    });
    Union::create(_fbb, &UnionArgs{
      mode,
      typeIds,
    })
  }
}
